
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
// Created via this command line: "C:\Users\emaslenkov\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\DLaB.EarlyBoundGenerator\crmsvcutil.exe" /url:"https://evgeniymtrial.api.crm4.dynamics.com" /namespace:"Auto.Common.Entities" /SuppressGeneratedCodeAttribute /out:"C:\navicon-project\AutoDealer\Auto.Common\Entities\OptionSets.cs" /codecustomization:"DLaB.CrmSvcUtilExtensions.OptionSet.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.OptionSet.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.OptionSet.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService,DLaB.CrmSvcUtilExtensions" 
//------------------------------------------------------------------------------

namespace Auto.Common.Entities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum auto_agreement_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Активный", 0)]
		Aktivnyj = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Неактивные", 1)]
		Neaktivnye = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum auto_auto_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Активный", 0)]
		Aktivnyj = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Неактивные", 1)]
		Neaktivnye = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum auto_brand_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Активный", 0)]
		Aktivnyj = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Неактивные", 1)]
		Neaktivnye = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum auto_communication_auto_type
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("E-mail", 1, "#0000ff")]
		E_mail = 635410001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Телефон", 0, "#0000ff")]
		Telefon = 635410000,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum auto_communication_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Активный", 0)]
		Aktivnyj = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Неактивные", 1)]
		Neaktivnye = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum auto_credit_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Активный", 0)]
		Aktivnyj = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Неактивные", 1)]
		Neaktivnye = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum auto_invoice_auto_type
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Автоматическое создание", 1, "#0000ff")]
		Avtomaticheskoe_sozdanie = 635410001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Ручное создание", 0, "#0000ff")]
		Ruchnoe_sozdanie = 635410000,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum auto_invoice_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Активный", 0)]
		Aktivnyj = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Неактивные", 1)]
		Neaktivnye = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum auto_model_auto_kp
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Автоматическая", 0, "#0000ff")]
		Avtomaticheskaya = 635410000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Механическая", 1, "#0000ff")]
		Mehanicheskaya = 635410001,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum auto_model_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Активный", 0)]
		Aktivnyj = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Неактивные", 1)]
		Neaktivnye = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_AccountRoleCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Деловой специалист", 0)]
		Delovoj_specialist = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Сотрудник", 1)]
		Sotrudnik = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Влияние", 2)]
		Vliyanie = 3,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_Address1_AddressTypeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Доставка", 1)]
		Dostavka = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Основной", 2)]
		Osnovnoj = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Получатель счета", 0)]
		Poluchatel_scheta = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Прочее", 3)]
		Prochee = 4,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_Address1_FreightTermsCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Бесплатно", 1)]
		Besplatno = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("CIF - стоимость, страхование и фрахт", 2)]
		CIF___stoimost_strahovanie_i_fraht = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("CIP - перевозка и страхование оплачены до", 3)]
		CIP___perevozka_i_strahovanie_oplacheny_do = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("CPT - перевозка оплачена до", 4)]
		CPT___perevozka_oplachena_do = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("DAF - доставка до границы", 5)]
		DAF___dostavka_do_granicy = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("DDP - с оплатой пошлины", 8)]
		DDP___s_oplatoj_poshliny = 10,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("DDU - без уплаты пошлины", 9)]
		DDU___bez_uplaty_poshliny = 11,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("DEQ - доставка с причала", 6)]
		DEQ___dostavka_s_prichala = 8,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("DES - доставка с судна", 7)]
		DES___dostavka_s_sudna = 9,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("EXW - франко-завод", 10)]
		EXW___franko_zavod = 12,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("FAS - франко вдоль борта судна", 11)]
		FAS___franko_vdol_borta_sudna = 13,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("FCA - франко-перевозчик", 12)]
		FCA___franko_perevozchik = 14,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("FOB - франко-борт", 0)]
		FOB___franko_bort = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_Address1_ShippingMethodCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Без доставки", 3)]
		Bez_dostavki = 24,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Карго-багаж", 4)]
		Kargo_bagazh = 25,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Курьер", 2)]
		Kurer = 19,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Линия", 1)]
		Liniya = 17,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Почта", 0)]
		Pochta = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Служба почтовой экспресс-доставки", 5)]
		Sluzhba_pochtovoj_ekspress_dostavki = 35,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_Address2_AddressTypeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Значение по умолчанию", 0)]
		Znachenie_po_umolchaniyu = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_Address2_FreightTermsCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Значение по умолчанию", 0)]
		Znachenie_po_umolchaniyu = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_Address2_ShippingMethodCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Значение по умолчанию", 0)]
		Znachenie_po_umolchaniyu = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_Address3_AddressTypeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Значение по умолчанию", 0)]
		Znachenie_po_umolchaniyu = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_Address3_FreightTermsCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Значение по умолчанию", 0)]
		Znachenie_po_umolchaniyu = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_Address3_ShippingMethodCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Значение по умолчанию", 0)]
		Znachenie_po_umolchaniyu = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_CustomerSizeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Значение по умолчанию", 0)]
		Znachenie_po_umolchaniyu = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_CustomerTypeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Значение по умолчанию", 0)]
		Znachenie_po_umolchaniyu = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_EducationCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Значение по умолчанию", 0)]
		Znachenie_po_umolchaniyu = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_FamilyStatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Не женат / не замужем", 0)]
		Ne_zhenat___ne_zamuzhem = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Разведен / разведена", 2)]
		Razveden___razvedena = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Вдовец / вдова", 3)]
		Vdovec___vdova = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Женат / замужем", 1)]
		ZHenat___zamuzhem = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_GenderCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("мужской", 0)]
		muzhskoj = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("женский", 1)]
		zhenskij = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_HasChildrenCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Значение по умолчанию", 0)]
		Znachenie_po_umolchaniyu = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_LeadSourceCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Значение по умолчанию", 0)]
		Znachenie_po_umolchaniyu = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_msdyn_decisioninfluencetag
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Авторитетный специалист", 1, "#FFD74B")]
		Avtoritetnyj_specialist = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Блокирующий", 2, "#FF0000")]
		Blokiruyuschij = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Лицо, принимающее решения", 0, "#32C100")]
		Lico_prinimayuschee_resheniya = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Неизвестно", 3, "#E1DFDD")]
		Neizvestno = 3,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_msdyn_orgchangestatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Не в организации", 1, "#0000ff")]
		Ne_v_organizacii = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Нет обратной связи", 0, "#0000ff")]
		Net_obratnoj_svyazi = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Пропустить", 2, "#0000ff")]
		Propustit = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_PaymentTermsCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("100% авансовый платеж%", 0)]
		_100PROCENT_avansovyj_platezhPROCENT = 33,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("50% авансовый платеж", 1)]
		_50PROCENT_avansovyj_platezh = 34,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Оплата по факту", 2)]
		Oplata_po_faktu = 35,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_PreferredAppointmentDayCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Четверг", 4)]
		CHetverg = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Понедельник", 1)]
		Ponedelnik = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Пятница", 5)]
		Pyatnica = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Среда", 3)]
		Sreda = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Суббота", 6)]
		Subbota = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Воскресенье", 0)]
		Voskresene = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Вторник", 2)]
		Vtornik = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_PreferredAppointmentTimeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("День", 1)]
		Den = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Утро", 0)]
		Utro = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Вечер", 2)]
		Vecher = 3,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_PreferredContactMethodCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Электронная почта", 1)]
		Elektronnaya_pochta = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Факс", 3)]
		Faks = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Любой", 0)]
		Lyuboj = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Почта", 4)]
		Pochta = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Телефон", 2)]
		Telefon = 3,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_ShippingMethodCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Значение по умолчанию", 0)]
		Znachenie_po_umolchaniyu = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Активный", 0)]
		Aktivnyj = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Неактивный", 1)]
		Neaktivnyj = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_TerritoryCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Значение по умолчанию", 0)]
		Znachenie_po_umolchaniyu = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum powerpagelanguages
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Английский", 11, "#0000ff")]
		Anglijskij = 1033,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Арабский", 0, "#0000ff")]
		Arabskij = 1025,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Баскский — Баскский", 1, "#0000ff")]
		Baskskij___Baskskij = 1069,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Болгарский — Болгария", 2, "#0000ff")]
		Bolgarskij___Bolgariya = 1026,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Чешский — Чешская Республика", 8, "#0000ff")]
		CHeshskij___CHeshskaya_Respublika = 1029,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Датский — Дания", 9, "#0000ff")]
		Datskij___Daniya = 1030,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Эстонский — Эстония", 12, "#0000ff")]
		Estonskij___Estoniya = 1061,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Финский — Финляндия", 13, "#0000ff")]
		Finskij___Finlyandiya = 1035,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Французский — Франция", 14, "#0000ff")]
		Francuzskij___Franciya = 1036,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Галисийский — Испания", 15, "#0000ff")]
		Galisijskij___Ispaniya = 1110,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Греческий — Греция", 17, "#0000ff")]
		Grecheskij___Greciya = 1032,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Хинди — Индия", 19, "#0000ff")]
		Hindi___Indiya = 1081,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Хорватский — Хорватия", 7, "#0000ff")]
		Horvatskij___Horvatiya = 1050,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Индонезийский — Индонезия", 21, "#0000ff")]
		Indonezijskij___Indoneziya = 1057,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Испанский (традиционная сортировка) — Испания", 39, "#0000ff")]
		Ispanskij_tradicionnaya_sortirovka___Ispaniya = 3082,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Итальянский — Италия", 22, "#0000ff")]
		Italyanskij___Italiya = 1040,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Иврит", 18, "#0000ff")]
		Ivrit = 1037,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Каталанский — Каталония", 3, "#0000ff")]
		Katalanskij___Kataloniya = 1027,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Казахский — Казахстан", 24, "#0000ff")]
		Kazahskij___Kazahstan = 1087,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Китайский — Гонконг (САР)", 5, "#0000ff")]
		Kitajskij___Gonkong_SAR = 3076,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Китайский — Китай", 4, "#0000ff")]
		Kitajskij___Kitaj = 2052,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Китайский — традиционное письмо", 6, "#0000ff")]
		Kitajskij___tradicionnoe_pismo = 1028,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Корейский — Республика Корея", 25, "#0000ff")]
		Korejskij___Respublika_Koreya = 1042,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Латышский — Латвия", 26, "#0000ff")]
		Latyshskij___Latviya = 1062,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Литовский — Литва", 27, "#0000ff")]
		Litovskij___Litva = 1063,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Малайский — Малайзия", 28, "#0000ff")]
		Malajskij___Malajziya = 1086,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Немецкий — Германия", 16, "#0000ff")]
		Nemeckij___Germaniya = 1031,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Нидерландский — Нидерланды", 10, "#0000ff")]
		Niderlandskij___Niderlandy = 1043,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Норвежский букмол — Норвегия", 29, "#0000ff")]
		Norvezhskij_bukmol___Norvegiya = 1044,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Польский — Польша", 30, "#0000ff")]
		Polskij___Polsha = 1045,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Португальский — Бразилия", 31, "#0000ff")]
		Portugalskij___Braziliya = 1046,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Португальский — Португалия", 32, "#0000ff")]
		Portugalskij___Portugaliya = 2070,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Румынский — Румыния", 33, "#0000ff")]
		Rumynskij___Rumyniya = 1048,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Русский — Россия", 34, "#0000ff")]
		Russkij___Rossiya = 1049,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Сербский (кириллица) — Сербия", 35, "#0000ff")]
		Serbskij_kirillica___Serbiya = 3098,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Сербский (латиница) — Сербия", 36, "#0000ff")]
		Serbskij_latinica___Serbiya = 2074,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Шведский — Швеция", 40, "#0000ff")]
		SHvedskij___SHveciya = 1053,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Словацкий — Словакия", 37, "#0000ff")]
		Slovackij___Slovakiya = 1051,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Словенский — Словения", 38, "#0000ff")]
		Slovenskij___Sloveniya = 1060,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Тайский — Таиланд", 41, "#0000ff")]
		Tajskij___Tailand = 1054,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Турецкий — Турция", 42, "#0000ff")]
		Tureckij___Turciya = 1055,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Украинский — Украина", 43, "#0000ff")]
		Ukrainskij___Ukraina = 1058,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Венгерский — Венгрия", 20, "#0000ff")]
		Vengerskij___Vengriya = 1038,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Вьетнамский — Вьетнам", 44, "#0000ff")]
		Vetnamskij___Vetnam = 1066,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Японский — Япония", 23, "#0000ff")]
		YAponskij___YAponiya = 1041,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum appaction_clienttype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Браузер", 0, "#0000ff")]
		Brauzer = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Мобильное приложение", 1, "#0000ff")]
		Mobilnoe_prilozhenie = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Почтовое приложение", 2, "#0000ff")]
		Pochtovoe_prilozhenie = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum card_sizes
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Маленький", 0, "#0000ff")]
		Malenkij = 200000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Средний", 1, "#0000ff")]
		Srednij = 200000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Большой", 2, "#0000ff")]
		Bolshoj = 200000002,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_forecastsettingsandsummary_msdyn_forecastjobstatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Выполнено", 0, "#0000ff")]
		Vypolneno = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Сбой данных", 1, "#0000ff")]
		Sboj_dannyh = 192350001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Сбой конвейера", 2, "#0000ff")]
		Sboj_konvejera = 192350002,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_knowledgemanagementsetting_msdyn_actionlist
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Связать / отменить связь статьи", 0, "#0000ff")]
		Svyazat___otmenit_svyaz_stati = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Копировать URL-адрес", 1, "#0000ff")]
		Kopirovat_URL_adres = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Связать статью и отправить URL-адрес по электронной почте", 2, "#0000ff")]
		Svyazat_statyu_i_otpravit_URL_adres_po_elektronnoj_pochte = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Связать статью и отправить содержимое статьи", 3, "#0000ff")]
		Svyazat_statyu_i_otpravit_soderzhimoe_stati = 3,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_oc_daysofweek
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Вс", 0, "#0000ff", "Sunday")]
		Vs = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Пн", 1, "#0000ff", "Monday")]
		Pn = 192350001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Вт", 2, "#0000ff", "Tuesday")]
		Vt = 192350002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Ср", 3, "#0000ff", "Wednesday")]
		Sr = 192350003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Чт", 4, "#0000ff", "Thursday")]
		CHt = 192350004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Пт", 5, "#0000ff", "Friday")]
		Pt = 192350005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Сб", 6, "#0000ff", "Saturday")]
		Sb = 192350006,
	}
}
